// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhpjlrdigtjpclkknuwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhocGpscmRpZ3RqcGNsa2tudXdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4Nzk1NDMsImV4cCI6MjA2NzQ1NTU0M30.3hwZcLLJa8b8ZqqCVqKU4DZYQ2FkoCOEb0sd0S9HZRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});